### ISSUE TITLE
CSVWriter Error ConcurrentModificationException

### ISSUE THREAD

**Issue by kgaertne** [NetworkSimulatorOrg/NetworkSimulator#14]
This error pops up when I run main without the two CSVWriter lines in Report commented out.

> java.util.ConcurrentModificationException
>         at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1630)
>         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
>         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
>         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
>         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
>         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
>         at CSVWriter.bufferWrite(CSVWriter.java:56)
>         at CSVWriter.appendLine(CSVWriter.java:65)
>         at CSVWriter.appendDataAsLine(CSVWriter.java:69)
>         at Report.logCollision(Report.java:51)
>         at Report.logReport(Report.java:35)
>         at Network.sendReport(Network.java:138)
>         at Node.sendReport(Node.java:126)
>         at ComputeNode.recvMsgThread(ComputeNode.java:83)
>         at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by weiffert** [comment]
I made the CSVWriter operations dealing with the array list synchronized. It was being called from multiple threads to write. I haven't personally ever seen the error, but I think it is resolved.

Reopen if it persists
