### ISSUE TITLE
Message Generation

### ISSUE THREAD

**Issue by weiffert** [NetworkSimulatorOrg/NetworkSimulator#19]
Where is probability of a message being generated done? Right now, it looks like each compute node always has a message to send. 

Formally: the probability a node has a message to send

I remember we decided to move this functionality into protocol instead of have it in send message. I am working on implementing TDMA, Token Passing, and Polling, and it would be useful to have this functionality in protocol. Token passing relies on the protocol being used regardless if there is a message to send. 

Does this sound good?

**Comment by kgaertne** [comment]
Right now it is just after a second of delay. I'm fine with it being moved into the Protocol. If you did this, would you create a new method for it to be called by sendMsg() or do it before returning a successful report?

**Comment by weiffert** [comment]
I see it now. I'm not sure what I'm going to do, but I think what I am striving for with Token Passing might require a thread handler to listen if the node is not ready to send. I'll let you know if I end up changing it. Thanks for pointing out its location

**Comment by weiffert** [comment]
I added a probability generation thing. It roughly works; well enough for the scope of this project
